### ISSUE TITLE
Roadmap 2.0

### ISSUE THREAD

**Issue by KittyGiraudel** [at-import/SassyLists#33]
- [x] Prefix all functions (#32)
- [x] Change all `false` returns to `null` in case of error (#34)
- [x] Add a dependency checker (#6)
- [x] Add `every()` and `some()` functions (#2)
- [x] Remove Compass dependency
